<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testmodels" nsURI="http:///org/eclipse/emf/parsley/tests/models/ParsleyTests.ecore/0.1.0"
    nsPrefix="testmodels">
  <eClassifiers xsi:type="ecore:EClass" name="TestContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classesWithName" upperBound="-1"
        eType="#//ClassWithName" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classesForControls" upperBound="-1"
        eType="#//ClassForControls" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contained" eType="#//TestContainer"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classesForTable" upperBound="-1"
        eType="#//ClassForTable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectsForValidation" upperBound="-1"
        eType="#//ClassForValidation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="multipleContained" upperBound="-1"
        eType="#//TestContainer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectsForDefaultValidation"
        upperBound="-1" eType="#//ClassForDefaultValidation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestEClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowercaseNameFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="UpperCaseNameFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="notChangeableFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derivedFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestEClassForFeatureName">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eField" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ABaseClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaseClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseClassFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseMultiReferenceFeature"
        upperBound="-1" eType="#//ClassWithName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DerivedClass" eSuperTypes="#//BaseClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derivedClassFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="derivedMultiReferenceFeature"
        upperBound="-1" eType="#//ClassWithName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DerivedDerivedClass" eSuperTypes="#//DerivedClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="MultipleInheritanceClass" eSuperTypes="#//TestEClass #//ABaseClass #//DerivedDerivedClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassForControls">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="booleanFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="booleanObjectFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="booleanDataTypeFeature"
        eType="#//BooleanDataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="booleanPrimitiveDataTypeFeature"
        eType="#//BooleanPrimitiveDataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enumFeature" eType="#//EnumForControls"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stringFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stringDataTypeFeature"
        eType="#//StringDataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stringFeatureWithDefault"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="default"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unserializableStringDataTypeFeature"
        eType="#//UnserializableStringDataType" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unchangeableStringFeature"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derivedStringFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceToClassWithName"
        eType="#//ClassWithName"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="multiReferenceFeature"
        upperBound="-1" eType="#//ClassWithName"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="featureMapEntries" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="group"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureMapEntries1" upperBound="-1"
        eType="#//ClassForFeatureMapEntry1" volatile="true" transient="true" derived="true"
        containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="group" value="#featureMapEntries"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureMapEntries2" upperBound="-1"
        eType="#//ClassForFeatureMapEntry2" volatile="true" transient="true" derived="true"
        containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="group" value="#featureMapEntries"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="singleContainmentReference"
        eType="#//ClassWithName" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bigDecimalFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bigIntegerFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doubleFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doubleObjectFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intObjectFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="floatFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="floatObjectFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortObjectFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="byteFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="byteObjectFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnumForControls">
    <eLiterals name="FIRST" value="1"/>
    <eLiterals name="SECOND" value="2"/>
    <eLiterals name="THIRD" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassWithName">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BooleanDataType" instanceClassName="java.lang.Boolean"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BooleanPrimitiveDataType" instanceClassName="boolean"/>
  <eClassifiers xsi:type="ecore:EDataType" name="StringDataType" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EDataType" name="UnserializableStringDataType" instanceClassName="java.lang.String"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaseClassForFeatureMapEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassForFeatureMapEntry1" eSuperTypes="#//BaseClassForFeatureMapEntry"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassForFeatureMapEntry2" eSuperTypes="#//BaseClassForFeatureMapEntry"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassForTable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classWithName1" eType="#//ClassWithName"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classWithName2" eType="#//ClassWithName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassForValidation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="NotEmpty"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="notEmpty" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassForDefaultValidation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="notEmpty" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="canBeEmpty" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
