<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testmodels" nsURI="http:///org/eclipse/emf/parsley/tests/models/ParsleyTests.ecore/0.1.0"
    nsPrefix="testmodels">
  <eClassifiers xsi:type="ecore:EClass" name="TestContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classesWithName" upperBound="-1"
        eType="#//ClassWithName" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classesForControls" upperBound="-1"
        eType="#//ClassForControls" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestEClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowercaseNameFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="UpperCaseNameFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="notChangeableFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derivedFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaseClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseClassFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseMultiReferenceFeature"
        upperBound="-1" eType="#//ClassWithName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DerivedClass" eSuperTypes="#//BaseClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derivedClassFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="derivedMultiReferenceFeature"
        upperBound="-1" eType="#//ClassWithName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassForControls">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="booleanFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="booleanObjectFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="booleanDataTypeFeature"
        eType="#//BooleanDataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="booleanPrimitiveDataTypeFeature"
        eType="#//BooleanPrimitiveDataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enumFeature" eType="#//EnumForControls"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stringFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceToClassWithName"
        eType="#//ClassWithName"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="multiReferenceFeature"
        upperBound="-1" eType="#//ClassWithName"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="featureMapEntries" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="group"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureMapEntries1" upperBound="-1"
        eType="#//ClassForFeatureMapEntry1" volatile="true" transient="true" derived="true"
        containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="group" value="#featureMapEntries"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureMapEntries2" upperBound="-1"
        eType="#//ClassForFeatureMapEntry2" volatile="true" transient="true" derived="true"
        containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="group" value="#featureMapEntries"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnumForControls">
    <eLiterals name="FIRST"/>
    <eLiterals name="SECOND"/>
    <eLiterals name="THIRD"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassWithName">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BooleanDataType" instanceClassName="java.lang.Boolean"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BooleanPrimitiveDataType" instanceClassName="boolean"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaseClassForFeatureMapEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassForFeatureMapEntry1" eSuperTypes="#//BaseClassForFeatureMapEntry"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassForFeatureMapEntry2" eSuperTypes="#//BaseClassForFeatureMapEntry"/>
</ecore:EPackage>
