/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.eclipse.emf.parsley.dsl.tests;

import org.eclipse.emf.parsley.dsl.model.ModelPackage;
import org.eclipse.xtext.diagnostics.Diagnostic;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.validation.ValidationTestHelper;
import org.junit.Test;
import org.junit.runner.RunWith;

import com.google.inject.Inject;

@RunWith(XtextRunner.class)
@InjectWith(EmfParsleyDslInjectorProvider.class)
public class EmfParsleyDslParsingTest extends EmfParsleyDslAbstractTest {

	@Inject
	private ValidationTestHelper validationTestHelper;

	@Test
	public void testEmptyModule() throws Exception {
		parseAndAssertNoError(inputs.emptyModule());
	}

	@Test
	public void testModuleWithExtends() throws Exception {
		parseAndAssertNoError(inputs.moduleWithExtends());
	}

	@Test
	public void testEmptyLabelProvider() throws Exception {
		parseAndAssertNoError(inputs.emptyLabelProvider());
	}

	@Test
	public void testEmptyLabelSpecifications() throws Exception {
		parseAndAssertNoError(inputs.emptyLabelSpecifications());
	}

	@Test
	public void testLabelSpecifications() throws Exception {
		parseAndAssertNoError(inputs.labelProvider());
	}

	@Test
	public void testEmptyLabelSpecificationsForColumns() throws Exception {
		parseAndAssertNoError(inputs.emptyLabelSpecificationsForColumns());
	}

	@Test
	public void testLabelSpecificationsForColumns() throws Exception {
		parseAndAssertNoError(inputs.tableLabelProvider());
	}

	@Test
	public void testDuplicateLabelSpecifications() throws Exception {
		parseAndAssertErrors(inputsWithErrors.duplicateLabelSpecifications());
	}

	@Test
	public void testPropertyDescriptionSpecifications() throws Exception {
		parseAndAssertNoError(inputs.featureCaptionProvider());
	}

	@Test
	public void testFormPropertyDescriptionSpecifications() throws Exception {
		parseAndAssertNoError(inputs.formFeatureCaptionProvider());
	}

	@Test
	public void testDialogPropertyDescriptionSpecifications() throws Exception {
		parseAndAssertNoError(inputs.dialogFeatureCaptionProvider());
	}

	@Test
	public void testWrongFeatureLabelSpecifications() throws Exception {
		var model = parseModel(inputsWithErrors.wrongPropertyDescriptionSpecifications());
		validationTestHelper.assertError(model,
			ModelPackage.eINSTANCE.getFeatureAssociatedExpression(),
			Diagnostic.LINKING_DIAGNOSTIC,
			"newArrayList"
		);
		validationTestHelper.assertError(model,
			ModelPackage.eINSTANCE.getFeatureAssociatedExpression(),
			Diagnostic.LINKING_DIAGNOSTIC,
			"getBooks"
		);
	}

	@Test
	public void testFeaturesSpecifications() throws Exception {
		parseAndAssertNoError(inputs.featuresProvider());
	}

	@Test
	public void testFormControlFactory() throws Exception {
		parseAndAssertNoError(inputs.formControlFactory());
	}

	@Test
	public void testDialogControlFactory() throws Exception {
		parseAndAssertNoError(inputs.dialogControlFactory());
	}

	@Test
	public void testProposalsSpecifications() throws Exception {
		parseAndAssertNoError(inputs.proposalCreator());
	}

	@Test
	public void testViewerContentProviderSpecifications() throws Exception {
		parseAndAssertNoError(inputs.viewerContentProvider());
	}

	@Test
	public void testEmptyViewsSpecifications() throws Exception {
		parseAndAssertNoError(inputs.emptyViewsSpecifications());
	}

	@Test
	public void testNonEmptyViewsSpecifications() throws Exception {
		parseAndAssertNoError(inputs.nonEmptyViewsSpecifications());
	}

	@Test
	public void testMultipleViewsSpecifications() throws Exception {
		parseAndAssertNoError(inputs.multipleViewsSpecifications());
	}

	@Test
	public void testConfigurator() throws Exception {
		parseAndAssertNoError(inputs.configuratorExample());
	}

}
