/*
 * generated by Xtext
 */
package org.eclipse.emf.parsley.examples.fowlerdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class StatemachineUiModule extends org.eclipse.emf.parsley.examples.fowlerdsl.ui.AbstractStatemachineUiModule {
	public StatemachineUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
