package org.eclipse.emf.parsley.dsl.tests;

import com.google.common.base.Objects;
import com.google.inject.Inject;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;
import org.eclipse.emf.parsley.dsl.EmfParsleyDslInjectorProvider;
import org.eclipse.emf.parsley.dsl.tests.EmfComponentsDslAbstractTests;
import org.eclipse.emf.parsley.dsl.tests.util.CustomCompilationTestHelper;
import org.eclipse.emf.parsley.dsl.tests.util.CustomCompilationTestHelper.Result;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.util.IAcceptor;
import org.eclipse.xtext.xbase.lib.Extension;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(EmfParsleyDslInjectorProvider.class)
@SuppressWarnings("all")
public class EmfComponentsDslGeneratorTests extends EmfComponentsDslAbstractTests {
  @Inject
  @Extension
  private CustomCompilationTestHelper _customCompilationTestHelper;
  
  @Test
  public void testEmptyModule() {
    CharSequence _emptyModule = this.inputs.emptyModule();
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package my.empty;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import org.eclipse.emf.parsley.EmfComponentsGuiceModule;");
    _builder.newLine();
    _builder.append("import org.eclipse.ui.plugin.AbstractUIPlugin;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("@SuppressWarnings(\"all\")");
    _builder.newLine();
    _builder.append("public class EmfComponentsGuiceModuleGen extends EmfComponentsGuiceModule {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("public EmfComponentsGuiceModuleGen(final AbstractUIPlugin plugin) {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("super(plugin);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    this.assertCorrectJavaCodeGeneration(_emptyModule, _builder, null, null, null, null, null, null, null);
  }
  
  @Test
  public void testModuleWithExtends() {
    CharSequence _moduleWithExtends = this.inputs.moduleWithExtends();
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package my.empty;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import org.eclipse.emf.parsley.dsl.tests.additional.MyTestGuiceModule;");
    _builder.newLine();
    _builder.append("import org.eclipse.ui.plugin.AbstractUIPlugin;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("@SuppressWarnings(\"all\")");
    _builder.newLine();
    _builder.append("public class EmfComponentsGuiceModuleGen extends MyTestGuiceModule {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("public EmfComponentsGuiceModuleGen(final AbstractUIPlugin plugin) {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("super(plugin);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    this.assertCorrectJavaCodeGeneration(_moduleWithExtends, _builder, null, null, null, null, null, null, null);
  }
  
  @Test
  public void testEmptyLabelProvider() {
    CharSequence _emptyLabelProvider = this.inputs.emptyLabelProvider();
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package my.empty;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import my.empty.ui.provider.LabelProviderGen;");
    _builder.newLine();
    _builder.append("import org.eclipse.emf.parsley.EmfComponentsGuiceModule;");
    _builder.newLine();
    _builder.append("import org.eclipse.jface.viewers.ILabelProvider;");
    _builder.newLine();
    _builder.append("import org.eclipse.ui.plugin.AbstractUIPlugin;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("@SuppressWarnings(\"all\")");
    _builder.newLine();
    _builder.append("public class EmfComponentsGuiceModuleGen extends EmfComponentsGuiceModule {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("public EmfComponentsGuiceModuleGen(final AbstractUIPlugin plugin) {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("super(plugin);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("  ");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("public Class<? extends ILabelProvider> bindILabelProvider() {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("return LabelProviderGen.class;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("package my.empty.ui.provider;");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("import com.google.inject.Inject;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.emf.parsley.ui.provider.ViewerLabelProvider;");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("@SuppressWarnings(\"all\")");
    _builder_1.newLine();
    _builder_1.append("public class LabelProviderGen extends ViewerLabelProvider {");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("@Inject");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public LabelProviderGen(final AdapterFactoryLabelProvider delegate) {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("super(delegate);");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("}");
    _builder_1.newLine();
    this.assertCorrectJavaCodeGeneration(_emptyLabelProvider, _builder, _builder_1, null, null, null, null, null, null);
  }
  
  @Test
  public void testEmptyPropertyDescriptionProvider() {
    CharSequence _emptyPropertyDescriptionProvider = this.inputs.emptyPropertyDescriptionProvider();
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package my.empty;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import my.empty.ui.provider.PropertyDescriptionProviderGen;");
    _builder.newLine();
    _builder.append("import org.eclipse.emf.parsley.EmfComponentsGuiceModule;");
    _builder.newLine();
    _builder.append("import org.eclipse.emf.parsley.ui.provider.PropertyDescriptionProvider;");
    _builder.newLine();
    _builder.append("import org.eclipse.ui.plugin.AbstractUIPlugin;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("@SuppressWarnings(\"all\")");
    _builder.newLine();
    _builder.append("public class EmfComponentsGuiceModuleGen extends EmfComponentsGuiceModule {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("public EmfComponentsGuiceModuleGen(final AbstractUIPlugin plugin) {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("super(plugin);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("  ");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("public Class<? extends PropertyDescriptionProvider> bindPropertyDescriptionProvider() {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("return PropertyDescriptionProviderGen.class;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("package my.empty.ui.provider;");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.emf.parsley.ui.provider.FeatureLabelProvider;");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("@SuppressWarnings(\"all\")");
    _builder_1.newLine();
    _builder_1.append("public class PropertyDescriptionProviderGen extends PropertyDescriptionProvider {");
    _builder_1.newLine();
    _builder_1.append("}");
    _builder_1.newLine();
    this.assertCorrectJavaCodeGeneration(_emptyPropertyDescriptionProvider, _builder, _builder_1, null, null, null, null, null, null);
  }
  
  @Test
  public void testEmptyLabelSpecifications() {
    CharSequence _emptyLabelSpecifications = this.inputs.emptyLabelSpecifications();
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package my.empty.ui.provider;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import com.google.inject.Inject;");
    _builder.newLine();
    _builder.append("import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;");
    _builder.newLine();
    _builder.append("import org.eclipse.emf.parsley.ui.provider.ViewerLabelProvider;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("@SuppressWarnings(\"all\")");
    _builder.newLine();
    _builder.append("public class LabelProviderGen extends ViewerLabelProvider {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("@Inject");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("public LabelProviderGen(final AdapterFactoryLabelProvider delegate) {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("super(delegate);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    this.assertCorrectJavaCodeGeneration(_emptyLabelSpecifications, 
      null, _builder, null, null, null, null, null, null);
  }
  
  @Test
  public void testLabelSpecifications() {
    CharSequence _labelSpecifications = this.inputs.labelSpecifications();
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package my.empty.ui.provider;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import com.google.inject.Inject;");
    _builder.newLine();
    _builder.append("import java.util.List;");
    _builder.newLine();
    _builder.append("import org.eclipse.emf.common.util.EList;");
    _builder.newLine();
    _builder.append("import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;");
    _builder.newLine();
    _builder.append("import org.eclipse.emf.parsley.examples.library.Book;");
    _builder.newLine();
    _builder.append("import org.eclipse.emf.parsley.examples.library.BookOnTape;");
    _builder.newLine();
    _builder.append("import org.eclipse.emf.parsley.examples.library.Borrower;");
    _builder.newLine();
    _builder.append("import org.eclipse.emf.parsley.examples.library.Lendable;");
    _builder.newLine();
    _builder.append("import org.eclipse.emf.parsley.examples.library.Library;");
    _builder.newLine();
    _builder.append("import org.eclipse.emf.parsley.examples.library.Writer;");
    _builder.newLine();
    _builder.append("import org.eclipse.emf.parsley.ui.provider.ViewerLabelProvider;");
    _builder.newLine();
    _builder.append("import org.eclipse.swt.graphics.ImageData;");
    _builder.newLine();
    _builder.append("import org.eclipse.xtext.xbase.lib.Functions.Function1;");
    _builder.newLine();
    _builder.append("import org.eclipse.xtext.xbase.lib.ListExtensions;");
    _builder.newLine();
    _builder.append("import org.eclipse.xtext.xbase.lib.StringExtensions;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("@SuppressWarnings(\"all\")");
    _builder.newLine();
    _builder.append("public class LabelProviderGen extends ViewerLabelProvider {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("@Inject");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("public LabelProviderGen(final AdapterFactoryLabelProvider delegate) {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("super(delegate);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("  ");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("public String text(final Library it) {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("return \"foo\";");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("  ");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("public String text(final Writer writer) {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("String _name = writer.getName();");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("return _name;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("  ");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("public String text(final Book it) {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("String _title = it.getTitle();");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("return _title;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("  ");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("public String text(final Lendable it) {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("int _copies = it.getCopies();");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("String _plus = (\"copies: \" + Integer.valueOf(_copies));");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("return _plus;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("  ");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("public String text(final Borrower it) {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("String _xblockexpression = null;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("{");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("EList<Lendable> _borrowed = it.getBorrowed();");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("final Function1<Lendable,Integer> _function = new Function1<Lendable,Integer>() {");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("public Integer apply(final Lendable b) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("int _copies = b.getCopies();");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("return Integer.valueOf(_copies);");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("};");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("List<Integer> _map = ListExtensions.<Lendable, Integer>map(_borrowed, _function);");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("final String buffer = (\"borrowed: \" + _map);");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("String _upperCase = buffer.toUpperCase();");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("_xblockexpression = (_upperCase);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("return _xblockexpression;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("  ");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("public String text(final BookOnTape it) {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("String _title = it.getTitle();");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("return _title;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("  ");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("public Object image(final Library it) {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("return \"library.jpeg\";");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("  ");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("public Object image(final Writer writer) {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("Object _xifexpression = null;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("String _name = writer.getName();");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("boolean _isNullOrEmpty = StringExtensions.isNullOrEmpty(_name);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("if (_isNullOrEmpty) {");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("_xifexpression = \"noname.gif\";");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("} else {");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("ImageData _imageData = new ImageData(\"writer.jpeg\");");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("_xifexpression = _imageData;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("return _xifexpression;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    this.assertCorrectJavaCodeGeneration(_labelSpecifications, 
      null, _builder, null, null, null, null, null, null);
  }
  
  @Test
  public void testPropertyDescriptionSpecifications() {
    CharSequence _propertyDescriptionSpecifications = this.inputs.propertyDescriptionSpecifications();
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package my.empty;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import my.empty.ui.provider.PropertyDescriptionProviderGen;");
    _builder.newLine();
    _builder.append("import org.eclipse.emf.parsley.EmfComponentsGuiceModule;");
    _builder.newLine();
    _builder.append("import org.eclipse.emf.parsley.ui.provider.PropertyDescriptionProvider;");
    _builder.newLine();
    _builder.append("import org.eclipse.ui.plugin.AbstractUIPlugin;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("@SuppressWarnings(\"all\")");
    _builder.newLine();
    _builder.append("public class EmfComponentsGuiceModuleGen extends EmfComponentsGuiceModule {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("public EmfComponentsGuiceModuleGen(final AbstractUIPlugin plugin) {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("super(plugin);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("  ");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("public Class<? extends PropertyDescriptionProvider> bindPropertyDescriptionProvider() {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("return PropertyDescriptionProviderGen.class;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("package my.empty.ui.provider;");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.emf.ecore.EStructuralFeature;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.emf.parsley.ui.provider.PropertyDescriptionProvider;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.xtext.xbase.lib.StringExtensions;");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("@SuppressWarnings(\"all\")");
    _builder_1.newLine();
    _builder_1.append("public class PropertyDescriptionProviderGen extends PropertyDescriptionProvider {");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public String text_Library_name(final EStructuralFeature it) {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return \"Name\";");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public String text_Library_books(final EStructuralFeature it) {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return \"Books\";");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public String text_Writer_lastName(final EStructuralFeature it) {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("String _name = it.getName();");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("String _firstUpper = StringExtensions.toFirstUpper(_name);");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return _firstUpper;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("}");
    _builder_1.newLine();
    this.assertCorrectJavaCodeGeneration(_propertyDescriptionSpecifications, _builder, null, _builder_1, null, null, null, null, null);
  }
  
  @Test
  public void testFeaturesSpecifications() {
    CharSequence _featuresSpecifications = this.inputs.featuresSpecifications();
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package my.empty;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import my.empty.ui.provider.FeaturesProviderGen;");
    _builder.newLine();
    _builder.append("import org.eclipse.emf.parsley.EmfComponentsGuiceModule;");
    _builder.newLine();
    _builder.append("import org.eclipse.emf.parsley.ui.provider.FeaturesProvider;");
    _builder.newLine();
    _builder.append("import org.eclipse.ui.plugin.AbstractUIPlugin;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("@SuppressWarnings(\"all\")");
    _builder.newLine();
    _builder.append("public class EmfComponentsGuiceModuleGen extends EmfComponentsGuiceModule {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("public EmfComponentsGuiceModuleGen(final AbstractUIPlugin plugin) {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("super(plugin);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("  ");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("public Class<? extends FeaturesProvider> bindFeaturesProvider() {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("return FeaturesProviderGen.class;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("package my.empty.ui.provider;");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.emf.parsley.ui.provider.EClassToEStructuralFeatureAsStringsMap;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.emf.parsley.ui.provider.FeaturesProvider;");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("@SuppressWarnings(\"all\")");
    _builder_1.newLine();
    _builder_1.append("public class FeaturesProviderGen extends FeaturesProvider {");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("@Override");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public void buildStringMap(final EClassToEStructuralFeatureAsStringsMap stringMap) {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("super.buildStringMap(stringMap);");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("stringMap.mapTo(\"org.eclipse.emf.parsley.examples.library.Library\",");
    _builder_1.newLine();
    _builder_1.append("      ");
    _builder_1.append("\"name\");");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("stringMap.mapTo(\"org.eclipse.emf.parsley.examples.library.Writer\",");
    _builder_1.newLine();
    _builder_1.append("      ");
    _builder_1.append("\"firstName\", \"lastName\", \"books\");");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("}");
    _builder_1.newLine();
    this.assertCorrectJavaCodeGeneration(_featuresSpecifications, _builder, null, null, _builder_1, null, null, null, null);
  }
  
  @Test
  public void testFormFeatureControlSpecifications() {
    CharSequence _formControlSpecifications = this.inputs.formControlSpecifications();
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package my.empty;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import my.empty.binding.FormFeatureControlFactoryGen;");
    _builder.newLine();
    _builder.append("import org.eclipse.emf.parsley.EmfComponentsGuiceModule;");
    _builder.newLine();
    _builder.append("import org.eclipse.emf.parsley.binding.FormControlFactory;");
    _builder.newLine();
    _builder.append("import org.eclipse.ui.plugin.AbstractUIPlugin;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("@SuppressWarnings(\"all\")");
    _builder.newLine();
    _builder.append("public class EmfComponentsGuiceModuleGen extends EmfComponentsGuiceModule {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("public EmfComponentsGuiceModuleGen(final AbstractUIPlugin plugin) {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("super(plugin);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("  ");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("public Class<? extends FormControlFactory> bindFormControlFactory() {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("return FormFeatureControlFactoryGen.class;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("package my.empty.binding;");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("import java.util.List;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.core.databinding.DataBindingContext;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.core.databinding.observable.value.IObservableValue;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.emf.common.util.EList;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.emf.parsley.binding.FormControlFactory;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.emf.parsley.examples.library.Book;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.emf.parsley.examples.library.Library;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.emf.parsley.examples.library.Writer;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.jface.databinding.swt.ISWTObservableValue;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.jface.databinding.swt.SWTObservables;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.swt.SWT;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.swt.widgets.Composite;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.swt.widgets.Control;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.swt.widgets.Label;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.ui.forms.widgets.FormToolkit;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.xtext.xbase.lib.Functions.Function1;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.xtext.xbase.lib.IterableExtensions;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.xtext.xbase.lib.ListExtensions;");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("@SuppressWarnings(\"all\")");
    _builder_1.newLine();
    _builder_1.append("public class FormFeatureControlFactoryGen extends FormControlFactory {");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public Control control_Library_name(final Library it) {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return null;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public Control control_Writer_books(final Writer it) {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("FormToolkit _toolkit = this.getToolkit();");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Composite _parent = this.getParent();");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("EList<Book> _books = it.getBooks();");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("final Function1<Book,String> _function = new Function1<Book,String>() {");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("public String apply(final Book it) {");
    _builder_1.newLine();
    _builder_1.append("          ");
    _builder_1.append("String _title = it.getTitle();");
    _builder_1.newLine();
    _builder_1.append("          ");
    _builder_1.append("return _title;");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("      ");
    _builder_1.append("};");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("List<String> _map = ListExtensions.<Book, String>map(_books, _function);");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("String _join = IterableExtensions.join(_map, \", \");");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Label _createLabel = _toolkit.createLabel(_parent, _join);");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return _createLabel;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public Control control_Writer_name(final DataBindingContext dataBindingContext, final IObservableValue observableValue) {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Control control = createControl_Writer_name();");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("dataBindingContext.bindValue(");
    _builder_1.newLine();
    _builder_1.append("    \t");
    _builder_1.append("createTarget_Writer_name(control),");
    _builder_1.newLine();
    _builder_1.append("    \t");
    _builder_1.append("observableValue);");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return control;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("protected Control createControl_Writer_name() {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("FormToolkit _toolkit = this.getToolkit();");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Composite _parent = this.getParent();");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Label _createLabel = _toolkit.createLabel(_parent, \"\");");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return _createLabel;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("protected IObservableValue createTarget_Writer_name(final Control it) {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("ISWTObservableValue _observeText = SWTObservables.observeText(it);");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return _observeText;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public Control control_Writer_firstName(final DataBindingContext dataBindingContext, final IObservableValue observableValue) {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Control control = createControl_Writer_firstName();");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("dataBindingContext.bindValue(");
    _builder_1.newLine();
    _builder_1.append("    \t");
    _builder_1.append("createTarget_Writer_firstName(control),");
    _builder_1.newLine();
    _builder_1.append("    \t");
    _builder_1.append("observableValue);");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return control;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("protected Control createControl_Writer_firstName() {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("FormToolkit _toolkit = this.getToolkit();");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Composite _parent = this.getParent();");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Label _createLabel = _toolkit.createLabel(_parent, \"\");");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return _createLabel;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("protected IObservableValue createTarget_Writer_firstName(final Control it) {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("ISWTObservableValue _observeText = SWTObservables.observeText(it, SWT.Modify);");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return _observeText;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("}");
    _builder_1.newLine();
    this.assertCorrectJavaCodeGeneration(_formControlSpecifications, _builder, null, null, null, _builder_1, null, null, null);
  }
  
  @Test
  public void testViewerContentProviderSpecifications() {
    CharSequence _viewerContentProviderSpecifications = this.inputs.viewerContentProviderSpecifications();
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package my.empty;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import my.empty.edit.ui.provider.ViewerContentProviderGen;");
    _builder.newLine();
    _builder.append("import org.eclipse.emf.parsley.EmfComponentsGuiceModule;");
    _builder.newLine();
    _builder.append("import org.eclipse.jface.viewers.IContentProvider;");
    _builder.newLine();
    _builder.append("import org.eclipse.ui.plugin.AbstractUIPlugin;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("@SuppressWarnings(\"all\")");
    _builder.newLine();
    _builder.append("public class EmfComponentsGuiceModuleGen extends EmfComponentsGuiceModule {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("public EmfComponentsGuiceModuleGen(final AbstractUIPlugin plugin) {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("super(plugin);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("  ");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("public Class<? extends IContentProvider> bindIContentProvider() {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("return ViewerContentProviderGen.class;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("package my.empty.edit.ui.provider;");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("import com.google.common.collect.Iterables;");
    _builder_1.newLine();
    _builder_1.append("import com.google.inject.Inject;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.emf.common.notify.AdapterFactory;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.emf.common.util.EList;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.emf.ecore.EObject;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.emf.parsley.edit.ui.provider.ViewerContentProvider;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.emf.parsley.examples.library.Book;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.emf.parsley.examples.library.Library;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.emf.parsley.examples.library.Writer;");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("@SuppressWarnings(\"all\")");
    _builder_1.newLine();
    _builder_1.append("public class ViewerContentProviderGen extends ViewerContentProvider {");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("@Inject");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public ViewerContentProviderGen(final AdapterFactory adapterFactory) {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("super(adapterFactory);");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public Object children(final Library it) {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("EList<Book> _books = it.getBooks();");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("EList<Writer> _writers = it.getWriters();");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Iterable<EObject> _plus = Iterables.<EObject>concat(_books, _writers);");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return _plus;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public Object children(final Writer writer) {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("EList<Book> _books = writer.getBooks();");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return _books;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public Object children(final Book it) {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Writer _author = it.getAuthor();");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return _author;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("}");
    _builder_1.newLine();
    this.assertCorrectJavaCodeGeneration(_viewerContentProviderSpecifications, _builder, null, null, null, null, _builder_1, null, null);
  }
  
  @Test
  public void testProposalSpecifications() {
    CharSequence _proposalsSpecifications = this.inputs.proposalsSpecifications();
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package my.empty;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import my.empty.binding.ProposalCreatorGen;");
    _builder.newLine();
    _builder.append("import org.eclipse.emf.parsley.EmfComponentsGuiceModule;");
    _builder.newLine();
    _builder.append("import org.eclipse.emf.parsley.binding.ProposalCreator;");
    _builder.newLine();
    _builder.append("import org.eclipse.ui.plugin.AbstractUIPlugin;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("@SuppressWarnings(\"all\")");
    _builder.newLine();
    _builder.append("public class EmfComponentsGuiceModuleGen extends EmfComponentsGuiceModule {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("public EmfComponentsGuiceModuleGen(final AbstractUIPlugin plugin) {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("super(plugin);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("  ");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("public Class<? extends ProposalCreator> bindProposalCreator() {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("return ProposalCreatorGen.class;");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("package my.empty.binding;");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("import java.util.ArrayList;");
    _builder_1.newLine();
    _builder_1.append("import java.util.List;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.emf.common.util.EList;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.emf.ecore.EStructuralFeature;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.emf.parsley.binding.ProposalCreator;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.emf.parsley.examples.library.Book;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.emf.parsley.examples.library.Borrower;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.emf.parsley.examples.library.EXTLibraryFactory;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.emf.parsley.examples.library.Library;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.emf.parsley.examples.library.Writer;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.xtext.xbase.lib.CollectionLiterals;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.xtext.xbase.lib.ObjectExtensions;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.xtext.xbase.lib.Procedures.Procedure1;");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("@SuppressWarnings(\"all\")");
    _builder_1.newLine();
    _builder_1.append("public class ProposalCreatorGen extends ProposalCreator {");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public List<? extends Object> proposals_Library_name(final Library it, final EStructuralFeature feature) {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("ArrayList<String> _newArrayList = CollectionLiterals.<String>newArrayList(\"foo\", \"bar\");");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return _newArrayList;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public List<? extends Object> proposals_Writer_books(final Writer it, final EStructuralFeature feature) {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("EList<Book> _books = it.getBooks();");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return _books;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public List<? extends Object> proposals_Book_author(final Book it, final EStructuralFeature feature) {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Writer _createWriter = EXTLibraryFactory.eINSTANCE.createWriter();");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("final Procedure1<Writer> _function = new Procedure1<Writer>() {");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("public void apply(final Writer it) {");
    _builder_1.newLine();
    _builder_1.append("          ");
    _builder_1.append("it.setName(\"Foo\");");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("      ");
    _builder_1.append("};");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Writer _doubleArrow = ObjectExtensions.<Writer>operator_doubleArrow(_createWriter, _function);");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Writer _createWriter_1 = EXTLibraryFactory.eINSTANCE.createWriter();");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("final Procedure1<Writer> _function_1 = new Procedure1<Writer>() {");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("public void apply(final Writer it) {");
    _builder_1.newLine();
    _builder_1.append("          ");
    _builder_1.append("it.setName(\"Bar\");");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("      ");
    _builder_1.append("};");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("Writer _doubleArrow_1 = ObjectExtensions.<Writer>operator_doubleArrow(_createWriter_1, _function_1);");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("ArrayList<Writer> _newArrayList = CollectionLiterals.<Writer>newArrayList(_doubleArrow, _doubleArrow_1);");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return _newArrayList;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("public List<? extends Object> proposals_Borrower_borrowed(final Borrower it, final EStructuralFeature feature) {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("List<Object> _defaultProposals = this.defaultProposals(feature);");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("final Procedure1<List<Object>> _function = new Procedure1<List<Object>>() {");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("public void apply(final List<Object> it) {");
    _builder_1.newLine();
    _builder_1.append("          ");
    _builder_1.append("Book _createBook = EXTLibraryFactory.eINSTANCE.createBook();");
    _builder_1.newLine();
    _builder_1.append("          ");
    _builder_1.append("final Procedure1<Book> _function = new Procedure1<Book>() {");
    _builder_1.newLine();
    _builder_1.append("              ");
    _builder_1.append("public void apply(final Book it) {");
    _builder_1.newLine();
    _builder_1.append("                ");
    _builder_1.append("it.setTitle(\"Fake Book\");");
    _builder_1.newLine();
    _builder_1.append("              ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("            ");
    _builder_1.append("};");
    _builder_1.newLine();
    _builder_1.append("          ");
    _builder_1.append("Book _doubleArrow = ObjectExtensions.<Book>operator_doubleArrow(_createBook, _function);");
    _builder_1.newLine();
    _builder_1.append("          ");
    _builder_1.append("it.add(_doubleArrow);");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("      ");
    _builder_1.append("};");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("final List<Object> p = ObjectExtensions.<List<Object>>operator_doubleArrow(_defaultProposals, _function);");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("return p;");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("}");
    _builder_1.newLine();
    this.assertCorrectJavaCodeGeneration(_proposalsSpecifications, _builder, null, null, null, null, null, _builder_1, null);
  }
  
  @Test
  public void testViewsSpecifications() {
    CharSequence _multipleViewsSpecifications = this.inputs.multipleViewsSpecifications();
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package my.test;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import org.eclipse.emf.parsley.EmfComponentsGuiceModule;");
    _builder.newLine();
    _builder.append("import org.eclipse.ui.plugin.AbstractUIPlugin;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("@SuppressWarnings(\"all\")");
    _builder.newLine();
    _builder.append("public class EmfComponentsGuiceModuleGen extends EmfComponentsGuiceModule {");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("public EmfComponentsGuiceModuleGen(final AbstractUIPlugin plugin) {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("super(plugin);");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
    _builder_1.newLine();
    _builder_1.append("<?eclipse version=\"3.4\"?>");
    _builder_1.newLine();
    _builder_1.append("<plugin>");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("<extension");
    _builder_1.newLine();
    _builder_1.append("\t      ");
    _builder_1.append("point=\"org.eclipse.ui.views\">");
    _builder_1.newLine();
    _builder_1.append("\t    ");
    _builder_1.append("<view");
    _builder_1.newLine();
    _builder_1.append("\t          ");
    _builder_1.append("category=\"org.eclipse.emf.parsley\"");
    _builder_1.newLine();
    _builder_1.append("\t          ");
    _builder_1.append("class=\"my.test.TestExecutableExtensionFactory:org.eclipse.emf.parsley.views.AbstractSaveableTreeView\"");
    _builder_1.newLine();
    _builder_1.append("\t          ");
    _builder_1.append("id=\"my.view.tree.part\"");
    _builder_1.newLine();
    _builder_1.append("\t          ");
    _builder_1.append("name=\"My Tree View\"");
    _builder_1.newLine();
    _builder_1.append("\t          ");
    _builder_1.append("restorable=\"true\">");
    _builder_1.newLine();
    _builder_1.append("\t    ");
    _builder_1.append("</view>");
    _builder_1.newLine();
    _builder_1.append("\t    ");
    _builder_1.append("<view");
    _builder_1.newLine();
    _builder_1.append("\t          ");
    _builder_1.append("category=\"my.view.category\"");
    _builder_1.newLine();
    _builder_1.append("\t          ");
    _builder_1.append("class=\"my.test.TestExecutableExtensionFactory:org.eclipse.emf.parsley.views.AbstractSaveableTreeFormView\"");
    _builder_1.newLine();
    _builder_1.append("\t          ");
    _builder_1.append("id=\"my.view.form.part\"");
    _builder_1.newLine();
    _builder_1.append("\t          ");
    _builder_1.append("name=\"My Tree Form View\"");
    _builder_1.newLine();
    _builder_1.append("\t          ");
    _builder_1.append("restorable=\"true\">");
    _builder_1.newLine();
    _builder_1.append("\t    ");
    _builder_1.append("</view>");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("</extension>");
    _builder_1.newLine();
    _builder_1.append("</plugin>");
    _builder_1.newLine();
    this.assertCorrectJavaCodeGeneration(_multipleViewsSpecifications, _builder, null, null, null, null, null, null, _builder_1);
  }
  
  private void assertCorrectJavaCodeGeneration(final CharSequence input, final CharSequence expectedModule, final CharSequence expectedLabelProvider, final CharSequence expectedPropertyDescriptionProvider, final CharSequence expectedFeatureProvider, final CharSequence expectedFormFeatureControlFactory, final CharSequence expectedViewerContentProvider, final CharSequence expectedProposalCreator, final CharSequence expectedPluginXmlGen) {
    final IAcceptor<Result> _function = new IAcceptor<Result>() {
        public void accept(final Result it) {
          Map<String,CharSequence> _allGeneratedResources = it.getAllGeneratedResources();
          Set<Entry<String,CharSequence>> _entrySet = _allGeneratedResources.entrySet();
          for (final Entry<String,CharSequence> e : _entrySet) {
            String _key = e.getKey();
            boolean _endsWith = _key.endsWith("ModuleGen.java");
            if (_endsWith) {
              boolean _notEquals = (!Objects.equal(expectedModule, null));
              if (_notEquals) {
                CharSequence _value = e.getValue();
                EmfComponentsDslGeneratorTests.this.assertEqualsStrings(expectedModule, _value);
              }
            } else {
              String _key_1 = e.getKey();
              boolean _endsWith_1 = _key_1.endsWith("PropertyDescriptionProviderGen.java");
              if (_endsWith_1) {
                boolean _notEquals_1 = (!Objects.equal(expectedPropertyDescriptionProvider, null));
                if (_notEquals_1) {
                  CharSequence _value_1 = e.getValue();
                  EmfComponentsDslGeneratorTests.this.assertEqualsStrings(expectedPropertyDescriptionProvider, _value_1);
                }
              } else {
                String _key_2 = e.getKey();
                boolean _endsWith_2 = _key_2.endsWith("FeaturesProviderGen.java");
                if (_endsWith_2) {
                  boolean _notEquals_2 = (!Objects.equal(expectedFeatureProvider, null));
                  if (_notEquals_2) {
                    CharSequence _value_2 = e.getValue();
                    EmfComponentsDslGeneratorTests.this.assertEqualsStrings(expectedFeatureProvider, _value_2);
                  }
                } else {
                  String _key_3 = e.getKey();
                  boolean _endsWith_3 = _key_3.endsWith("LabelProviderGen.java");
                  if (_endsWith_3) {
                    boolean _notEquals_3 = (!Objects.equal(expectedLabelProvider, null));
                    if (_notEquals_3) {
                      CharSequence _value_3 = e.getValue();
                      EmfComponentsDslGeneratorTests.this.assertEqualsStrings(expectedLabelProvider, _value_3);
                    }
                  } else {
                    String _key_4 = e.getKey();
                    boolean _endsWith_4 = _key_4.endsWith("FormFeatureControlFactoryGen.java");
                    if (_endsWith_4) {
                      boolean _notEquals_4 = (!Objects.equal(expectedFormFeatureControlFactory, null));
                      if (_notEquals_4) {
                        CharSequence _value_4 = e.getValue();
                        EmfComponentsDslGeneratorTests.this.assertEqualsStrings(expectedFormFeatureControlFactory, _value_4);
                      }
                    } else {
                      String _key_5 = e.getKey();
                      boolean _endsWith_5 = _key_5.endsWith("ViewerContentProviderGen.java");
                      if (_endsWith_5) {
                        boolean _notEquals_5 = (!Objects.equal(expectedViewerContentProvider, null));
                        if (_notEquals_5) {
                          CharSequence _value_5 = e.getValue();
                          EmfComponentsDslGeneratorTests.this.assertEqualsStrings(expectedViewerContentProvider, _value_5);
                        }
                      } else {
                        String _key_6 = e.getKey();
                        boolean _endsWith_6 = _key_6.endsWith("ProposalCreatorGen.java");
                        if (_endsWith_6) {
                          boolean _notEquals_6 = (!Objects.equal(expectedProposalCreator, null));
                          if (_notEquals_6) {
                            CharSequence _value_6 = e.getValue();
                            EmfComponentsDslGeneratorTests.this.assertEqualsStrings(expectedProposalCreator, _value_6);
                          }
                        } else {
                          String _key_7 = e.getKey();
                          boolean _endsWith_7 = _key_7.endsWith(".xml_emfparsley_gen");
                          if (_endsWith_7) {
                            boolean _notEquals_7 = (!Objects.equal(expectedPluginXmlGen, null));
                            if (_notEquals_7) {
                              CharSequence _value_7 = e.getValue();
                              EmfComponentsDslGeneratorTests.this.assertEqualsStrings(expectedPluginXmlGen, _value_7);
                            }
                          } else {
                            CharSequence _value_8 = e.getValue();
                            String _plus = ("unexpected generated code: " + _value_8);
                            Assert.fail(_plus);
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
          it.compileToJava();
        }
      };
    this._customCompilationTestHelper.compileAll(input, _function);
  }
}
