/*
* generated by Xtext
*/
package org.eclipse.emf.parsley.examples.fowlerdsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class StatemachineOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
