/*
 * generated by Xtext
 */
package org.eclipse.emf.parsley.examples.fowlerdsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class StatemachineRuntimeModule extends org.eclipse.emf.parsley.examples.fowlerdsl.AbstractStatemachineRuntimeModule {

}
