/*
* generated by Xtext
*/
package org.eclipse.emf.parsley.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class EmfParsleyDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.eclipse.emf.parsley.dsl.ui.internal.EmfParsleyDslActivator.getInstance().getInjector("org.eclipse.emf.parsley.dsl.EmfParsleyDsl");
	}
	
}
