/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.eclipse.emf.parsley.dsl.ui.wizard;

import org.eclipse.ui.dialogs.WizardNewProjectCreationPage;

public class EmfParsleyDslWizardNewProjectCreationPage extends WizardNewProjectCreationPage {

	public EmfParsleyDslWizardNewProjectCreationPage(String pageName) {
		super(pageName);
	}

}
