/*
 * generated by Xtext 2.33.0
 */
package org.eclipse.emf.parsley.dsl.ide;


/**
 * Use this class to register ide components.
 */
public class EmfParsleyDslIdeModule extends AbstractEmfParsleyDslIdeModule {
}
