/*
 * generated by Xtext 2.33.0
 */
package org.eclipse.emf.parsley.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.emf.parsley.dsl.EmfParsleyDslRuntimeModule;
import org.eclipse.emf.parsley.dsl.EmfParsleyDslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class EmfParsleyDslIdeSetup extends EmfParsleyDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new EmfParsleyDslRuntimeModule(), new EmfParsleyDslIdeModule()));
	}
	
}
