/*
 * generated by Xtext 2.11.0
 */
package org.eclipse.emf.parsley.dsl.ide


/**
 * Use this class to register ide components.
 */
class EmfParsleyDslIdeModule extends AbstractEmfParsleyDslIdeModule {
}
