/*
 * generated by Xtext 2.33.0
 */
package org.eclipse.emf.parsley.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class EmfParsleyDslStandaloneSetup extends EmfParsleyDslStandaloneSetupGenerated {

	public static void doSetup() {
		new EmfParsleyDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
