/*
* generated by Xtext
*/
package org.eclipse.emf.parsley.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.emf.parsley.dsl.services.EmfParsleyDslGrammarAccess;

public class EmfParsleyDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private EmfParsleyDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclipse.emf.parsley.dsl.parser.antlr.internal.InternalEmfParsleyDslParser createParser(XtextTokenStream stream) {
		return new org.eclipse.emf.parsley.dsl.parser.antlr.internal.InternalEmfParsleyDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public EmfParsleyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EmfParsleyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
