/*
* generated by Xtext
*/
package org.eclipse.emf.parsley.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class EmfParsleyDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/eclipse/emf/parsley/dsl/parser/antlr/internal/InternalEmfParsleyDsl.tokens");
	}
}
