/*
 * generated by Xtext
 */
package org.eclipse.emf.parsley.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipse.emf.parsley.dsl.ui.internal.EmfParsleyDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EmfParsleyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return EmfParsleyDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return EmfParsleyDslActivator.getInstance().getInjector(EmfParsleyDslActivator.ORG_ECLIPSE_EMF_PARSLEY_DSL_EMFPARSLEYDSL);
	}
	
}
