name: Java CI with Maven (RAP)

on:
  push:
    paths-ignore:
     - '**.md'
  pull_request:
    paths-ignore:
     - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.5.0
    - name: Set up JDK 11
      uses: actions/setup-java@v3.6.0
      with:
        java-version: 11
        distribution: temurin
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2
          !~/.m2/**/*parsley*
        key: ${{ runner.os }}-rap-m2-${{ hashFiles('**/pom.xml', '**/*.target') }}
        restore-keys: ${{ runner.os }}-rap-m2-
      # for the examples our Parsley bundles would be put in .m2
      # so we exclude them from the cache
    - name: Build with Maven
      run: >
        ./mvnw -f releng/org.eclipse.emf.parsley.parent/pom.xml
        -Prap-build
        clean verify
    - name: Build Examples with Maven
      run: >
        ./mvnw -f releng/org.eclipse.emf.parsley.parent/pom.xml
        -Prap-examples
        clean verify
    - name: Archive Target Platform example
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: rap-examples-test-${{ runner.os }}
        path: '**/org.eclipse.emf.parsley.targetplatform/rap-examples-test.target'
