name: Java CI with Maven (RAP)

on:
  push:
    paths-ignore:
     - 'README.md'
  pull_request:
    paths-ignore:
     - 'README.md'

jobs:
  build:
    env:
      DISPLAY: :1
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.5.0
    - name: Set up JDK 11
      uses: actions/setup-java@v3.6.0
      with:
        java-version: 11
        distribution: temurin
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.target') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Build with Maven
      run: >
        mvn -f releng/org.eclipse.emf.parsley.parent/pom.xml
        -Prap-build
        clean verify
    - name: Build Examples with Maven
      run: >
        mvn -f releng/org.eclipse.emf.parsley.parent/pom.xml
        -Prap-examples
        clean verify
