name: Java CI with Maven (Windows)

on:
  push:
    paths-ignore:
      - 'README.md'
    # Sequence of patterns matched against refs/heads
    branches:
      # Push events on the main branch
      - master
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2.5.0
    - name: Set up JDK 11
      uses: actions/setup-java@v3.6.0
      with:
        java-version: 11
        distribution: temurin
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.target') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Build with Maven
      run: >
        mvn -f releng/org.eclipse.emf.parsley.parent/pom.xml
        clean verify
        '-Dswtbot.tests.skip=true'
      # The full suite of SWTBot tests is too flaky on Windows
    - name: Archive UI Tests Screenshots
      uses: actions/upload-artifact@v2
      if: ${{ failure() || cancelled() }}
      with:
        name: screenshots-${{ runner.os }}
        path: '**/screenshots'
    - name: Archive Logs
      uses: actions/upload-artifact@v2
      if: ${{ failure() || cancelled() }}
      with:
        name: logs-${{ runner.os }}
        path: '**/target/work/data/.metadata/.log'